resources:
  - name: repo_res
    type: GitRepo
    configuration:
      gitProvider: Github
      path: harshkumar1/test_repo

pipelines:
  - name: test_repo
    steps:
      - name: docker_build_bash
        type: Bash
        configuration:
          inputResources:
            - name: repo_res
        execution:
          onExecute:
            - cd $res_repo_res_path
            - docker buildx build -t test1 --load .