resources:
  - name: propertyBag_1
    type: PropertyBag
    configuration:
      property1: "jfrog"
      property2: "pipelines"

pipelines:
  - name: pipe_env_variable_sample
    configuration:
      environmentVariables:
        readOnly:
          pipe_env_variable: value1

    steps:
      - name: test_step_env_variables
        type: Bash
        configuration:
          environmentVariables:
            step_env_variable: step_value10
        inputResources:
          - propertyBag_1
        execution:
          onExecute:
            - echo ${pipe_env_variable}
            - echo ${step_env_variable}
            - echo ${property1}
            - echo ${property2}