resources:
  - name: test_repo_propertyBag_1
    type: PropertyBag
    configuration:
      property1: "jfrog"
      property2: "pipelines"

pipelines:
  - name: pipe_env_variable_sample
    configuration:
      environmentVariables:
        readOnly:
          pipe_env_variable: value1

    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: test_repo_propertyBag_1
        execution:
          onExecute:
            - echo ${property1}
            - echo ${property2}
  
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          environmentVariables:
            step_env_variable: step_value10
          outputResources:
            - name: test_repo_propertyBag_1
        execution:
          onExecute:
            - echo ${pipe_env_variable}
            - echo ${step_env_variable}
            - write_output test_repo_propertyBag_1 property1="GithubActions"

      - name: step_3
        type: Bash
        configuration:
          inputResources:
            - name: test_repo_propertyBag_1
        execution:
          onExecute:
            - echo ${property1}
            - echo ${property2}