resources:
  - name: test_repo_propertyBag_1
    type: PropertyBag
    configuration:
      property1: "jfrog"
      property2: "pipelines"

pipelines:
  - name: pipe_env_variable_sample
    configuration:
      environmentVariables:
        readOnly:
          pipe_env_variable: value1

    steps:
      # - name: step_1
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: test_repo_propertyBag_1
      #   execution:
      #     onExecute:
      #       - echo ${property1}
      #       - echo ${property2}
  
      - name: step_2
        type: Bash
        configuration:
          # inputSteps:
          #   - name: step_1
          environmentVariables:
            step_env_variable: step_value10
          inputResources:
            - name: repo_res
          outputResources:
            - name: test_repo_propertyBag_1
        execution:
          onExecute:
            - echo ${pipe_env_variable}
            - echo ${step_env_variable}
            - values="GithubAction"
            - write_output test_repo_propertyBag_1 property1=${values}
            - cd $res_repo_res_resourcePath/
            - ls
      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
          inputResources:
            - name: test_repo_propertyBag_1
        execution:
          onExecute:
            - echo ${property1}
            - echo ${property2}