resources:
  - name: repo_res
    type: GitRepo
    configuration:
      gitProvider: hk_github
      path: harshkumar1/test_repo

pipelines:
  - name: test_repo
    steps:
    #  - name: docker_build_bash
    #    type: Bash
    #    configuration:
    #      inputResources:
    #        - name: repo_res
    #    execution:
    #      onExecute:
    #        - cd $res_repo_res_resourcePath
    #        - docker build -f ./test-within-docker/Dockerfile .
    #        - id=$(docker images --filter "label=testDocker" -q)
    #        - docker create --name testcontainer $id
    #        - docker cp testcontainer:/tmp/surefire-reports ./testresults
    #        - save_tests ./testresults
    #        - docker rm testcontainer
    #        - docker rmi $id
      - name: upload_result
        type: UploadArtifact
        configuration:
          #affinityGroup: group
          #inputSteps:
          #  - name: merge_files
          inputResources:
            - name: repo_res
          targetPath: example-repo-local/TEST-com.jfrogpipe.demo.AppTest.${run_number}.xml
          sourcePath: $res_repo_res_resourcePath/test-within-docker/surefire-reports/TEST-com.jfrogpipe.demo.AppTest.xml
          regExp: true
          integrations:
            - name: hk_artifactory
        execution:
          onStart:
            -  |
              (while true; do
                ps -eo pid,pcpu,cmd --sort=-pcpu | head -n 10 >> cpu_usage.log
                sleep 1
                done) &
            - echo "Uploading..."
            - var=$(find $res_repo_res_resourcePath/ -name "*.xml" -print0 | sed -r 's/TEST-(.+).xml/\1/')
            - echo $var
          onSuccess:
            - echo "Uploaded"
          onFailure:
            - echo "Failed to upload"
          onComplete:
            - cat cpu_usage.log