pipelines:
  - name: pipe_env_variable_sample
    configuration:
      environmentVariables:
        readOnly:
          pipe_env_variable: value1

    steps:
      - name: test_step_env_variables
        type: Bash
        execution:
          onExecute:
            - echo ${pipe_env_variable}