pipelines:
  - name: pipe_env_variable_sample
    configuration:
      environmentVariables:
        readOnly:
          pipe_env_variable: value1
    steps:
      - name: pipe_env_variable
        execution:
          onExecute:
            - echo ${pipe_env_variable}